FROM fedora:33 as sheep_base

### get wget git etc

RUN dnf -y groupinstall "Development Tools" "Development Libraries";
RUN dnf -y install \
    git \
    wget \
    cmake;

###### get fftw3 (needed for TFHE)
RUN dnf install -y fftw-devel

####### install intel-tbb for parallelisation
RUN dnf install -y tbb-devel

### Create base dir for FHE-libraries
RUN mkdir -p SHEEP/backend/lib/

###### get autoconf (needed for PALISADE)
RUN dnf install -y autoconf

###### build PALISADE
RUN cd SHEEP/backend/lib; git clone https://gitlab.com/palisade/palisade-release.git
RUN cd SHEEP/backend/lib/palisade-release/; git submodule sync --recursive; git submodule update --init  --recursive
RUN mkdir SHEEP/backend/lib/palisade-release/build
RUN cd SHEEP/backend/lib/palisade-release/build; export CC=gcc; export CXX=g++; cmake ..
RUN cd SHEEP/backend/lib/palisade-release/build; make -j2; make install;

# ###### get gmp (needed for HElib)
RUN dnf -y install m4
RUN version=6.2.0; wget https://gmplib.org/download/gmp/gmp-$version.tar.xz; \
    tar -xvf gmp-$version.tar.xz; \
    cd gmp-$version; export CC=gcc; export CXX=g++; ./configure; make -j4; make install

###### get ntl (needed for HElib)
RUN version=10.5.0; wget https://libntl.org/ntl-$version.tar.gz; \
    tar -xvzf ntl-$version.tar.gz; \
    cd ntl-$version/src; export CC=gcc; export CXX=g++; \
    ./configure NTL_GMP_LIP=on NTL_EXCEPTIONS=on; make -j4; make install

###### get cpprestsdk (for the REST API)
RUN dnf -y install cpprest-devel

###### build SEAL
RUN cd SHEEP/backend/lib; version=3.6.3; \
    wget -qO- https://github.com/microsoft/SEAL/archive/refs/tags/v$version.tar.gz | tar xvz; \
    cd SEAL-$version; export CC=gcc; export CXX=g++ ; \
    cmake -S . -B build; cmake --build build; cmake --install build

###### build TFHE
RUN cd SHEEP/backend/lib; git clone --recurse-submodules https://github.com/tfhe/tfhe.git
RUN cd SHEEP/backend/lib/tfhe; git reset --hard a65271bc8f5f0015c71351ed8746dd8eec051e29
RUN cd SHEEP/backend/lib/tfhe; git submodule update --init

RUN rm -fr SHEEP/backend/lib/tfhe/build
RUN mkdir -p SHEEP/backend/lib/tfhe/build
RUN cd SHEEP/backend/lib/tfhe/build; export CC=gcc; export CXX=g++; cmake ../src -DENABLE_TESTS=on -DENABLE_FFTW=on -DCMAKE_BUILD_TYPE=optim -DENABLE_NAYUKI_PORTABLE=off -DENABLE_SPQLIOS_AVX=off -DENABLE_SPQLIOS_FMA=off -DENABLE_NAYUKI_AVX=off
RUN cd SHEEP/backend/lib/tfhe/build; make -j4; make install;

###### build HElib
RUN cd SHEEP/backend/lib; git clone --recurse-submodules https://github.com/shaih/HElib.git
RUN cd SHEEP/backend/lib/HElib; git reset --hard 9c50908a3538f5df77df523e525e1f9841f22eb2
RUN cd SHEEP/backend/lib/HElib; git submodule update --init

RUN cd SHEEP/backend/lib/HElib/src ; export CC=gcc; export CXX=g++; make clean; make -j4;
