FROM ubuntu:20.04 as sheep_base

RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get -y install tzdata

### get wget git etc

RUN apt-get update; apt-get -y install \
    git \
    wget \
    cmake \
    gcc-9 \
    g++-9 \
    build-essential

###### get fftw3 (needed for TFHE)
RUN apt-get install -y libfftw3-dev

####### install intel-tbb for parallelisation
RUN apt-get -y install libtbb-dev

###### install PALISADE
RUN apt-get -y install lzip
RUN apt-get -y install flex
RUN apt-get -y install bison
RUN git clone https://gitlab.com/palisade/palisade-release.git PALISADE;
RUN cd PALISADE; git reset --hard v1.5.0
RUN cd PALISADE && ./configure.sh
# Monkey patch to fix 'error: moving a local object in a return statement prevents copy elision' in the source code
RUN cd PALISADE && find Makefile* \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i 's/-Werror/-Werror -Wno-pessimizing-move/g'
RUN cd PALISADE && echo "@@@@@" && g++ --version && CC=gcc-9 CXX=g++-9 make -j4

# ###### get gmp (needed for HElib)
RUN apt -y install m4
RUN version=6.2.0; wget https://gmplib.org/download/gmp/gmp-$version.tar.xz; \
    tar -xvf gmp-$version.tar.xz; \
    cd gmp-$version; export CC=gcc-9; export CXX=g++-9; ./configure; make -j4; make install

###### get ntl (needed for HElib)
RUN version=10.5.0; wget https://libntl.org/ntl-$version.tar.gz; \
    tar -xvzf ntl-$version.tar.gz; \
    cd ntl-$version/src; export CC=gcc-9; export CXX=g++-9; \
    ./configure NTL_GMP_LIP=on NTL_EXCEPTIONS=on; make -j4; make install

###### get cpprestsdk (for the REST API)
RUN apt-get update
RUN apt-get -y install libssl-dev
RUN apt-get -y install libboost-all-dev
RUN apt-get update
RUN git clone --recurse-submodules  https://github.com/Microsoft/cpprestsdk.git casablanca
RUN cd casablanca/Release; mkdir build.debug; cd build.debug; \
    export CC=gcc-9; export CXX=g++-9; cmake .. -DCMAKE_BUILD_TYPE=Debug; make install -j4

###### build SEAL
RUN version=3.6.3; \
wget -qO- https://github.com/microsoft/SEAL/archive/refs/tags/v$version.tar.gz | tar xvz; \
cd SEAL-$version; export CC=gcc-9; export CXX=g++-9 ; cmake -S . -B build; cmake --build build


###### get and build libpaillier
RUN wget http://hms.isi.jhu.edu/acsc/libpaillier/libpaillier-0.8.tar.gz
RUN tar -xvzf libpaillier-0.8.tar.gz
RUN cd libpaillier-0.8 ; ./configure; make -j4; make install

RUN mkdir -p SHEEP/backend/lib/

###### build TFHE
RUN cd SHEEP/backend/lib; git clone --recurse-submodules https://github.com/tfhe/tfhe.git
RUN cd SHEEP/backend/lib/tfhe; git reset --hard a65271bc8f5f0015c71351ed8746dd8eec051e29
RUN cd SHEEP/backend/lib/tfhe; git submodule update --init

RUN rm -fr SHEEP/backend/lib/tfhe/build
RUN mkdir -p SHEEP/backend/lib/tfhe/build
RUN cd SHEEP/backend/lib/tfhe/build; export CC=gcc-9; export CXX=g++-9; cmake ../src -DENABLE_TESTS=on -DENABLE_FFTW=on -DCMAKE_BUILD_TYPE=optim -DENABLE_NAYUKI_PORTABLE=off -DENABLE_SPQLIOS_AVX=off -DENABLE_SPQLIOS_FMA=off -DENABLE_NAYUKI_AVX=off
RUN cd SHEEP/backend/lib/tfhe/build; make -j4; make install;

###### build HElib
RUN cd SHEEP/backend/lib; git clone --recurse-submodules https://github.com/shaih/HElib.git
RUN cd SHEEP/backend/lib/HElib; git reset --hard 9c50908a3538f5df77df523e525e1f9841f22eb2
RUN cd SHEEP/backend/lib/HElib; git submodule update --init

RUN cd SHEEP/backend/lib/HElib/src ; export CC=gcc-9; export CXX=g++-9; make clean; make -j4;
