find_path(PALISADE_INCLUDE_DIR palisade)
find_library(PALISADE_CORE_LIBRARY NAMES PALISADEcore)
find_library(PALISADE_PKE_LIBRARY NAMES PALISADEpke)

#set(PALISADE_FOUND TRUE)
set(PALISADE_INCLUDE_DIRS ${PALISADE_INCLUDE_DIR}/palisade/pke ${PALISADE_INCLUDE_DIR}/palisade/core ${PALISADE_INCLUDE_DIR}/palisade)
message(STATUS "KEK PALISADE_INCLUDE_DIRS ${PALISADE_INCLUDE_DIRS}")
set(PALISADE_LIBRARIES ${PALISADE_CORE_LIBRARY} ${PALISADE_PKE_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PALISADE DEFAULT_MSG
                                  PALISADE_CORE_LIBRARY PALISADE_INCLUDE_DIR)

mark_as_advanced(PALISADE_CORE_LIBRARY PALISADE_PKE_LIBRARY PALISADE_INCLUDE_DIR)
